### ISSUE TITLE
Submit with enter button

### ISSUE THREAD

**Issue by teberl** [iredchuk/wiki-langlinks-web#4]
I also wanna start a search by hitting the enter button in addition to click GO.

**Comment by iredchuk** [comment]
I think we could even ditch the button.

**Comment by teberl** [comment]
For now i would keep the button, since most users are used to have a button.
But i will create a ticket to restyle the button.
Atm i am thinking about the same way google goes. Put the button at the end of the text input with a magnifying glass.
