### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by teberl** [iredchuk/wiki-langlinks-web#6]
Make the UI mobile friendly to make fun used on phones and tablets.

**Comment by zyxdef** [comment]
A pane layout option in _Global Options_ with a single, sliding pane containing source files, console, terminal, environment etc. would allow a perhaps decent work with client on mobile and a remote R server connected.  Wouldn't it?

**Comment by teberl** [comment]
Since this topic is to general we transform it into a milestone where we plan concrete steps to improve the usability on mobile and desktop devices.
